CREATE TABLE SUITE_MethodSummaryReport (id INT NOT NULL AUTO_INCREMENT, 
    SUITE_NAME VARCHAR(400),
    TEST_NAME VARCHAR(400), 
    ITEST_CONTEXT VARCHAR(400), 
    TEST_RESULTS VARCHAR(40),
    DATUM DATE NOT NULL, 
    COMMENTS VARCHAR(400),
    PRIMARY KEY (ID));